# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Audacity.Audacity
Publisher: Audacity
PackageName: Audacity
Author: Audacity
ShortDescription: An easy-to-use, multi-track audio editor and recorder.
Moniker: audacity
Tags:
- audacity
- admin
- audio
- dsp
- foss
- cross-platform
PackageUrl: https://www.audacityteam.org/
License: GPL 2.0 or later
LicenseUrl: https://www.audacityteam.org/about/license
MinimumOSVersion: 10.0.0.0
PackageVersion: 3.0.2
InstallerType: inno
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/audacity/audacity/releases/download/Audacity-3.0.2/audacity-win-3.0.2.exe
  InstallerSha256: 2FA8E586A339D9DA8DCF49C21F4CD1CBAA24691B1DCC0D02F6C9F451AC8BEA47
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

