PackageIdentifier: TimKosse.FileZillaClientNightly
PackageName: FileZilla Client Nightly
Moniker: filezilla-nightly
PackageVersion: 3.53.1-20210424
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2021 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
ShortDescription: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
PackageUrl: https://filezilla-project.org/
Installers:
- Architecture: x64
  InstallerUrl: https://filezilla-project.org/nightlies/2021-04-24/win64/FileZilla_3_setup.exe
  InstallerSha256: c965dc4c51f60e0bcc809e7533e42efdf1f008a3b68fc46e1e0824603ed6be9d
  InstallerType: nullsoft
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
