# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: AgileBits.1Password
PackageVersion: 7.6.797
PackageName: 1Password
Publisher: AgileBits
License: AgileBits, Inc. Terms of Service
LicenseUrl: https://1password.com/legal/terms-of-service/
Moniker: 1password
Tags:
- password
ShortDescription: 1Password remembers all your passwords for you, and keeps them safe and secure behind the one password that only you know.
PackageUrl: https://1password.com/
Installers:
- Architecture: neutral
  InstallerUrl: https://c.1password.com/dist/1P/win6/1PasswordSetup-7.6.797.exe
  InstallerSha256: 2E49B568ADD34872801C0B66E23F4F8B47BC13ADAEF088D74FC5D70A4E0DCB84
  InstallerType: exe
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

