# Automatically updated by the winget bot at 2021/Apr/22
PackageIdentifier: Google.ChromeBeta
Publisher: Google
PackageName: Google Chrome Beta
Author: Google
ShortDescription: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
Moniker: chrome-beta
Tags:
- Browser
- Google
- Chromium
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
PackageUrl: https://www.google.com/chrome/beta/
License: Proprietary freeware, based on open source components
LicenseUrl: https://www.google.com/chrome/terms/
MinimumOSVersion: 10.0.0.0
PackageVersion: 68.94.19
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 7E6CB22B15103666374FDD6E4B2FF13FF4F78BD006E9A07767833D5BBCF574EA
  Scope: machine
  InstallerLocale: en-US
  ProductCode: "{0575054B-2ECB-338C-869D-87E4DA51E237}"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
