PackageIdentifier: LutzRoeder.Netron
PackageVersion: 4.9.0
PackageName: Netron
Publisher: Lutz Roeder
Moniker: netron
ShortDescription: Visualizer for neural network, deep learning, and machine learning models
License: Copyright (c) Lutz Roeder
PackageUrl: https://github.com/lutzroeder/netron
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v4.9.0/Netron-Setup-4.9.0.exe
  InstallerSha256: BD23F4E82EE2D28405119BF3C9FDB37893B2C0556898C25804807791B6416E95
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
