# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageName: Playnite
Publisher: Playnite
PackageIdentifier: Playnite.Playnite
PackageVersion: "8.12"
Moniker: playnite
License: MIT
ShortDescription: An open source video game library manager and launcher with support for 3rd party libraries like Steam, GOG, Origin, Battle.net and Uplay. Includes game emulation support, providing one unified interface for your games.
PackageUrl: https://playnite.link/
LicenseUrl: https://raw.githubusercontent.com/JosefNemec/Playnite/master/LICENSE.md
Installers:
- Architecture: x86
  InstallerUrl: https://playnite.link/update/stable/8.12/Playnite812.exe
  InstallerSha256: 6D9BDCB8F99E5DD24F3295EE0007BB613A59581FB33E063B5ED1C8EF4645FC12
  InstallerType: inno
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

