# Automatically updated by the winget bot at 2021/Apr/28
PackageIdentifier: SoftPerfect.SoftPerfectNetworkScanner
Publisher: SoftPerfect
Author: SoftPerfect
PackageName: SoftPerfectNetworkScanner
PackageVersion: 8.0.2
License: © 2000–2020 SoftPerfect Pty Ltd, Australia
InstallerType: exe
Tags:
- network
- scanner
- snmp
ShortDescription: Powerful multipurpose network administration tool for Windows and macOS.
PackageUrl: https://www.softperfect.com/products/networkscanner/
Installers:
- Architecture: x64
  InstallerUrl: https://www.softperfect.com/download/files/netscan_setup.exe
  InstallerSha256: 4CF88B57C1B2B09723A25893D5F029AF70FB3C656C7672D92D1AC2D4FD258E92
  InstallerSwitches:
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
