PackageIdentifier: LutzRoeder.Netron
PackageVersion: 4.8.9
PackageName: Netron
Publisher: Lutz Roeder
Moniker: netron
ShortDescription: Visualizer for neural network, deep learning, and machine learning models
License: Copyright (c) Lutz Roeder
PackageUrl: https://github.com/lutzroeder/netron
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v4.8.9/Netron-Setup-4.8.9.exe
  InstallerSha256: C16F92379286A450D58406413B0E41AC34FA3BEE6393A6895F9780FA22C2480D
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
