# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: calibre.calibre
PackageVersion: 5.9.0
Installers:
- Architecture: x64
  InstallerUrl: https://download.calibre-ebook.com/5.9.0/calibre-64bit-5.9.0.msi
  InstallerSha256: CDE1B5EC27E0B56E5B2E618B9EBE7B62731872F020A04A3A1B55D17C43BD4F55
  InstallerType: msi
  ProductCode: "{6DB760DC-BEC5-4727-AA50-722D2881725E}"
- Architecture: x86
  InstallerUrl: https://download.calibre-ebook.com/5.9.0/calibre-5.9.0.msi
  InstallerSha256: 3CAC89869FDE550B1EB38A5BAD14AC360C67423904D11FA57184EC47DD8E81EC
  InstallerType: msi
  ProductCode: "{26732898-7BE1-4C68-A061-D71563AB9685}"
ManifestType: installer
ManifestVersion: 1.0.0

