# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: ProtonVPN.ProtonVPN
PackageVersion: 1.20.1
PackageName: ProtonVPN
Publisher: ProtonVPN
License: Copyright (c) Proton Technologies AG
Moniker: protonvpn
Tags:
- vpn
ShortDescription: High-speed Swiss VPN that safeguards your privacy.
PackageUrl: https://protonvpn.com/
Installers:
- Architecture: x64
  InstallerUrl: https://protonvpn.com/download/ProtonVPN_win_v1.20.1.exe
  InstallerSha256: 49914F57716FEC426BC8A552C2034A41F8D1E76BE02FEEF99D57F26C11BEF7EE
  InstallerType: exe
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

