# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageName: Kindle
Publisher: Amazon
PackageIdentifier: Amazon.Kindle
PackageVersion: 1.31.60170
Moniker: kindle
License: Copyright (c) Amazon.com, Inc. or its affiliates
Tags:
- reading
- epub
- reader
- books
- amazon
- kindle
InstallerType: exe
ShortDescription: Amazon.Kindle
Description: The Kindle app is available for most major smartphones, tablets and computers. That means with our free Kindle reading apps, you can buy a Kindle book once, and read it on any device with the Kindle app installed*. You can also read that same Kindle book on a Kindle device if you own one.
PackageUrl: https://www.amazon.co.uk/kindle-dbs/fd/kcp
LicenseUrl: https://www.amazon.com/gp/help/customer/display.html?nodeId=200699130
Installers:
- Architecture: x86
  InstallerUrl: https://s3.amazonaws.com/kindleforpc/60170/KindleForPC-installer-1.31.60170.exe
  InstallerSha256: 3C5EAACE1A3DB0E67231791181B24174FA2978B2B37FF6A25D238299C1CB29DA
  InstallerType: nullsoft
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

