# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: ProtonTechnologies.ProtonVPN
PackageVersion: 1.20.1
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x86
    InstallerType: exe
    InstallerUrl: https://github.com/ProtonVPN/win-app/releases/download/1.20.1/ProtonVPN_win_v1.20.1.exe
    InstallerSha256: 49914F57716FEC426BC8A552C2034A41F8D1E76BE02FEEF99D57F26C11BEF7EE
    InstallerSwitches:
      Silent: /quiet
      SilentWithProgress: /quiet
    ProductCode: "{43B895EF-2E68-43A5-AF20-6FBAFDD52E05}"
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
