# Automatically updated by the winget bot at 2021/Apr/21
PackageIdentifier: Blitz.Blitz
Publisher: Blitz
PackageName: Blitz
PackageVersion: 1.14.3.77
License: Custom use license
InstallerType: exe
LicenseUrl: https://www.blitz.gg/terms-of-service
Moniker: blitz.gg
Tags:
- lol
- blitz
- league
- legends
ShortDescription: Blitz App - Your personal gaming coach
PackageUrl: https://blitz.gg/
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://blitz.gg/download/win
  InstallerSha256: 699A329B7CB35FB94538E864159AEC507BB77AC6349B23A1872A3F78F3370C35
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
